### ISSUE TITLE
Revisit naming of accessors for new newtypes

### ISSUE THREAD

**Issue by Shimuuar** [bos/statistics#110]
Copied from #108

> Somewhat aside, would getPValue be more clear named getAlphaValue? Or is it that the CL represents both alpha-values and p-values?

It's interesting idea I need to think about it. I don't like current naming of accessor functions. @jsermeno if you have any further comment on the their naming, please write them here. Good naming is hard

**Comment by jsermeno** [comment]
Naming definitely is difficult. I just saw that there is actually a `PValue` type as well, which I hadn't realized before. I think it makes a lot of sense for confidence level, α (significance level), and σ (sigma) to be wrapped in the `CL` type—while having different accessors to get at each one—and keeping the idea of p-value separate (which is already done to a large extent). Where `confidence level == (1 - α)`,  σ is an alternative representation to α, and p-value is the result of a significance test that is compared to α.

Maybe something like:

```
newtype PValue = PValue Double deriving(..)
newtype CL = CL Double deriving(..)

mkCL :: Double -> CL
mkCLE :: Double -> Maybe CL
mkCLFromSignificanceLevel :: Double -> CL
mkCLFromSignificanceLevel :: Double -> Maybe CL
mkCLFromSigma ::  Double -> CL
mkCLFromSigmaE :: Double -> Maybe CL
mkCLFromSigma1 :: Double -> CL
mkCLFromSigma1E :: Double -> Maybe CL

getConfLevel :: CL -> Double
getSignificanceLevel :: CL -> Double
getSigma :: CL -> Double
getSigma1 :: CL -> Double

mkPValue :: Double -> PValue
mkPValueE :: Double -> Maybe PValue
getPValue :: PValue -> Double

isSignificant :: PValue -> CL -> Bool 

-- Remove function 'asCL' so you can't convert between 'PValue' and 'CL'. 
-- Remove function 'asPValue' for same reasons.
```

I removed the type parameters only because the sigma conversion functions seemed to require doubles anyways, and it seems like you should be able to fluidly convert between these representations. 

```
>>> let cl = cl95
>>> cl
significanceLevel 0.05
>>> cl == mkCLFromSignificanceLevel 0.05
True
>>> getSigma cl
1.9599639845400545
>>> getConfLevel cl
0.95
>>> getSignificanceLevel cl
0.05
```
Is having `E` at the end of a function that returns `Maybe` a thing? I've been looking for some sort of convention like that.

**Comment by Shimuuar** [comment]
Thanks a lot! A lot of it was due to transition: Double→CL→CL & PValue.

> Is having E at the end of a function that returns Maybe a thing? I've been looking for some sort of convention like that.

I made this convention up but you're of course welcome to use it (:
